# Generated by Django 2.2.3 on 2021-04-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='', max_length=500)),
                ('url', models.CharField(default='', max_length=500, unique=True)),
                ('comment', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('UnCrawl', 'UnCrawl'), ('Crawled', 'Crawled')], default='UnCrawl', max_length=16)),
            ],
        ),
    ]
