# Generated by Django 2.2.3 on 2021-04-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderurl',
            name='records',
            field=models.IntegerField(default=0),
        ),
    ]
