# Generated by Django 2.2.3 on 2021-04-07 02:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0002_spiderurl_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderurl',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
