HTTP_HEADER = 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36'
BTC_COM_PAGE_KEY = "BTCCOMPAGEKEY"
ETHERSCAN_TAG_PAGE = "ETHERSCANTAGPAGE"
YITAIFANG_TAG_PAGE = "YITAIFANG_TAG_PAGE"
BLOCKDIR_OFFSET = "blockdir-offset"